export type Media={id:number;title:string;overview:string;poster:string;backdrop:string;rating:number;year:string;type:"movie"|"tv"};
export type Episode={id:number;number:number;name:string;overview:string;still:string;airDate:string;runtime?:number};
export type Season={id:number;number:number;name:string;episodeCount:number;poster:string;airDate:string};
export type Detail=Media&{genres:string[];runtime?:number;status?:string;seasons?:Season[];trailerKey?:string;recommendations:Media[]};
const IMG='https://image.tmdb.org/t/p/original', IMG500='https://image.tmdb.org/t/p/w500';
export function normalize(x:any,forced?:"movie"|"tv"):Media{const type=forced||(x.media_type==='tv'||(!x.title&&x.name)?'tv':'movie');const d=x.release_date||x.first_air_date||'';return{id:Number(x.id),title:x.title||x.name||'Sem título',overview:x.overview||'Sinopse não disponível.',poster:x.poster_path?IMG500+x.poster_path:'',backdrop:x.backdrop_path?IMG+x.backdrop_path:'',rating:Number(x.vote_average||0),year:d?String(d).slice(0,4):'',type}}
async function api(path:string){const t=process.env.TMDB_READ_TOKEN;if(!t)return null;const r=await fetch('https://api.themoviedb.org/3'+path,{headers:{Authorization:`Bearer ${t}`,accept:'application/json'},next:{revalidate:1800}});return r.ok?r.json():null}
const demo:Media[]=[{id:1,title:'Horizonte Final',overview:'Uma missão espacial precisa decidir entre voltar para casa ou atravessar o desconhecido.',poster:'',backdrop:'',rating:8.4,year:'2026',type:'movie'},{id:2,title:'Distrito 9 PM',overview:'Uma investigadora descobre uma rede de segredos que atravessa a cidade.',poster:'',backdrop:'',rating:8.1,year:'2026',type:'tv'}];
export async function getHome(){const [a,b,c,d]=await Promise.all([api('/trending/all/week?language=pt-BR'),api('/movie/now_playing?language=pt-BR&region=BR'),api('/tv/popular?language=pt-BR'),api('/movie/top_rated?language=pt-BR')]);if(!a||!b||!c||!d)return{hero:demo[0],trending:demo,movies:demo.filter(x=>x.type==='movie'),tv:demo.filter(x=>x.type==='tv'),top:demo,demo:true};const trend=a.results.slice(0,18).map((x:any)=>normalize(x));return{hero:trend.find((x:Media)=>x.backdrop)||trend[0],trending:trend,movies:b.results.slice(0,18).map((x:any)=>normalize(x,'movie')),tv:c.results.slice(0,18).map((x:any)=>normalize(x,'tv')),top:d.results.slice(0,18).map((x:any)=>normalize(x,'movie')),demo:false}}
export async function searchMedia(q:string){const d=await api(`/search/multi?language=pt-BR&include_adult=false&query=${encodeURIComponent(q)}`);return d?(d.results||[]).filter((x:any)=>x.media_type==='movie'||x.media_type==='tv').slice(0,30).map((x:any)=>normalize(x)):[]}
export async function getDetail(type:"movie"|"tv",id:string):Promise<Detail|null>{const [d,v,r]=await Promise.all([api(`/${type}/${id}?language=pt-BR`),api(`/${type}/${id}/videos?language=pt-BR`),api(`/${type}/${id}/recommendations?language=pt-BR`)]);if(!d)return null;const tr=(v?.results||[]).find((x:any)=>x.site==='YouTube'&&x.type==='Trailer')||(v?.results||[]).find((x:any)=>x.site==='YouTube');return{...normalize(d,type),genres:(d.genres||[]).map((g:any)=>g.name),runtime:type==='movie'?d.runtime:d.episode_run_time?.[0],status:d.status,seasons:type==='tv'?(d.seasons||[]).filter((s:any)=>s.season_number>0).map((s:any)=>({id:s.id,number:s.season_number,name:s.name,episodeCount:s.episode_count,poster:s.poster_path?IMG500+s.poster_path:'',airDate:s.air_date||''})):[],trailerKey:tr?.key,recommendations:(r?.results||[]).slice(0,14).map((x:any)=>normalize(x,type))}}
export async function getSeason(id:string,n:string):Promise<Episode[]>{const d=await api(`/tv/${id}/season/${n}?language=pt-BR`);return d?(d.episodes||[]).map((e:any)=>({id:e.id,number:e.episode_number,name:e.name||`Episódio ${e.episode_number}`,overview:e.overview||'Sinopse não disponível.',still:e.still_path?IMG500+e.still_path:'',airDate:e.air_date||'',runtime:e.runtime})):[]}
